"""Core data models for CtxFlow.

Defines the schema-agnostic Node and Edge types, framework configuration,
query result wrappers, and provenance/contradiction result types.
All types use dataclasses with sensible defaults.
"""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Set, Tuple


def _generate_id() -> str:
    """Generate a unique node/edge identifier."""
    return uuid.uuid4().hex[:12]


def _now() -> float:
    """Current timestamp as a float (seconds since epoch)."""
    return time.time()


# ---------------------------------------------------------------------------
# Node
# ---------------------------------------------------------------------------

class NodeStatus(str, Enum):
    """Validity status of a node in the graph."""

    ACTIVE = "active"
    SUPERSEDED = "superseded"
    CONTESTED = "contested"


@dataclass
class Node:
    """A single context unit in the graph.

    Attributes:
        id: Unique identifier (auto-generated if omitted).
        content: Raw content of the context unit.
        summary: Short summary (may be auto-generated by an Extractor).
        embedding: Optional dense vector for future embedding-based retrieval.
        tags: Set of free-form string tags for lightweight matching.
        node_type: Open vocabulary type (e.g. "observation", "decision").
        timestamp: Creation time (seconds since epoch).
        metadata: Arbitrary key-value pairs for consumer-specific data.
        last_accessed: Timestamp of the most recent query hit.
        access_count: Number of times this node has been returned by a query.
        status: Validity status — ``"active"``, ``"superseded"``, or ``"contested"``.
        superseded_by: ID of the node that supersedes this one (if any).
    """

    content: str
    id: str = field(default_factory=_generate_id)
    summary: str = ""
    embedding: Optional[List[float]] = None
    tags: Set[str] = field(default_factory=set)
    node_type: str = "generic"
    timestamp: float = field(default_factory=_now)
    metadata: Dict[str, Any] = field(default_factory=dict)
    last_accessed: float = 0.0
    access_count: int = 0
    status: str = NodeStatus.ACTIVE
    superseded_by: Optional[str] = None

    def touch(self) -> None:
        """Update access tracking (called when this node is returned by a query)."""
        self.last_accessed = _now()
        self.access_count += 1


# ---------------------------------------------------------------------------
# Edge
# ---------------------------------------------------------------------------

@dataclass
class Edge:
    """A directed relationship between two nodes.

    Attributes:
        source_id: ID of the source node.
        target_id: ID of the target node.
        relation_type: Open vocabulary relation (e.g. ``"caused_by"``,
            ``"references"``, ``"supersedes"``, ``"contradicts"``).
        weight: Strength of the relationship (0–1), typically Jaccard similarity
                for auto-linked edges.
        timestamp: Creation time (seconds since epoch).
        metadata: Arbitrary key-value pairs (e.g. ``{"confidence": 0.85,
            "evidence": "..."}`` for contradiction edges).
    """

    source_id: str
    target_id: str
    relation_type: str = "related_to"
    weight: float = 1.0
    timestamp: float = field(default_factory=_now)
    metadata: Dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

@dataclass
class CtxFlowConfig:
    """Framework-level configuration with sensible defaults.

    All governance, scoring, and structural knobs live here so consumers
    can tune behaviour without touching framework internals.
    """

    # -- Ingestion --
    max_link_k: int = 5
    """Top-k most tag-similar nodes to auto-link on ingest."""

    min_link_similarity: float = 0.1
    """Minimum Jaccard similarity to create an implicit link."""

    # -- Governance --
    degree_cap_enabled: bool = True
    """Whether to enforce a maximum fan-out per node."""

    degree_cap: int = 50
    """Maximum number of outgoing edges per node (if enabled)."""

    degree_normalization: bool = False
    """Divide relevance scores by (degree + 1) at query time."""

    # -- Query / Scoring --
    alpha: float = 0.5
    """Weight for tag_overlap in the scoring function."""

    beta: float = 0.3
    """Weight for recency in the scoring function."""

    gamma: float = 0.2
    """Weight for proximity (BFS) in the scoring function."""

    bfs_max_depth: int = 3
    """Maximum BFS hops from anchor node for proximity scoring."""

    # -- Embedding (optional) --
    embedding_enabled: bool = False
    """When True, use embedding cosine similarity as a scoring signal."""

    embedding_model: str = "text-embedding-3-small"
    """Identifier of the embedding model (informational, not used directly)."""

    # -- Contradiction detection --
    contradiction_detection: bool = False
    """When True, run contradiction detection during ingest."""

    contradiction_similarity_threshold: float = 0.3
    """Minimum tag similarity to consider a node as a contradiction candidate."""

    contradiction_confidence_threshold: float = 0.7
    """Minimum LLM confidence to apply a supersession edge."""

    # -- Pruning --
    prune_min_access: int = 0
    """Nodes with access_count <= this value are candidates for pruning."""

    prune_age_weight: float = 0.4
    """Weight for node age in the staleness score."""

    prune_access_weight: float = 0.3
    """Weight for access frequency in the staleness score."""

    prune_recency_weight: float = 0.3
    """Weight for last-accessed recency in the staleness score."""

    def validate(self) -> None:
        """Raise ValueError if config is invalid."""
        if not (0 <= self.alpha <= 1 and 0 <= self.beta <= 1 and 0 <= self.gamma <= 1):
            raise ValueError("Scoring weights (alpha, beta, gamma) must be in [0, 1].")
        total = self.alpha + self.beta + self.gamma
        if abs(total - 1.0) > 1e-6:
            raise ValueError(
                f"Scoring weights must sum to 1.0, got {total:.4f}."
            )
        if self.degree_cap < 1:
            raise ValueError("degree_cap must be >= 1.")
        if self.max_link_k < 0:
            raise ValueError("max_link_k must be >= 0.")
        if self.bfs_max_depth < 1:
            raise ValueError("bfs_max_depth must be >= 1.")


# ---------------------------------------------------------------------------
# Query result
# ---------------------------------------------------------------------------

@dataclass
class QueryResult:
    """A node returned by a query, annotated with its computed score.

    Attributes:
        node: The matched Node.
        score: Composite relevance score.
        score_breakdown: Per-component scores for transparency.
    """

    node: Node
    score: float = 0.0
    score_breakdown: Dict[str, float] = field(default_factory=dict)

    def __repr__(self) -> str:
        return (
            f"QueryResult(node_id={self.node.id!r}, "
            f"score={self.score:.4f}, "
            f"type={self.node.node_type!r})"
        )


# ---------------------------------------------------------------------------
# Contradiction / supersession result
# ---------------------------------------------------------------------------

@dataclass
class ContradictionResult:
    """Result of checking whether two nodes contradict or supersede each other.

    Attributes:
        existing_node_id: ID of the existing node being compared against.
        relation: Detected relation — ``"supersedes"``, ``"contradicts"``,
            ``"supports"``, or ``"unrelated"``.
        confidence: LLM-assigned confidence in the relation (0–1).
        evidence: Free-text reasoning from the LLM.
    """

    existing_node_id: str
    relation: str  # "supersedes" | "contradicts" | "supports" | "unrelated"
    confidence: float = 0.0
    evidence: str = ""


# ---------------------------------------------------------------------------
# Provenance / research trace
# ---------------------------------------------------------------------------

@dataclass
class ProvenanceStep:
    """A single step in a backward provenance walk.

    Attributes:
        node: The node at this step.
        edge: The edge that connects this node to the previous step
            (``None`` for the root node).
    """

    node: Node
    edge: Optional[Edge] = None


@dataclass
class ProvenanceChain:
    """A backward chain of provenance from a root node to its sources.

    Attributes:
        root: The node where the trace started.
        steps: Ordered list of provenance steps (root first, sources last).
        contradictions: Nodes and edges that contradict or supersede
            nodes in the chain.
    """

    root: Node
    steps: List[ProvenanceStep] = field(default_factory=list)
    contradictions: List[Tuple[Node, Edge]] = field(default_factory=list)


@dataclass
class ResearchTrace:
    """Full provenance and contradiction context for a query answer.

    Attributes:
        answer_node_id: ID of the node whose trace this represents.
        supporting_chain: Backward provenance chain.
        superseded_claims: Nodes marked as superseded in the chain.
        contradicting_claims: Nodes that contradict claims in the chain.
        source_papers: Leaf nodes that represent paper references.
    """

    answer_node_id: str
    supporting_chain: ProvenanceChain
    superseded_claims: List[Node] = field(default_factory=list)
    contradicting_claims: List[Tuple[Node, Edge]] = field(default_factory=list)
    source_papers: List[Node] = field(default_factory=list)
